# -*- coding: utf-8 -*-
"""SahrulFirdaus.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5XFqNGHHscefz1-x1dn3FJf6Ei816pd
"""

print("1. buat variabel list dengan value: nama kendaraan, jenis, cc, warna, roda")
a=["motor","roda dua", "500 cc", "hitam"]
print(a)
print(" ")
print("* tambahkan dari list tersebut di belakang dengan value harga dan tipe kendaraan")
a.append("20.000.000")
print(a)
a.append("metic")
print(a)
print(" ")
print("* tambahkan setelah jenis kendaraan dengan value merk kendaraan")
a.insert(2,"beat")
print(a)

print("2. buat program phyton dengan case untuk menghitung bangun datar")

ket='''selamat datang di aplikasi menghitung bangun datar.
masukan pilihan:
1. untuk menghitung luas persegi
2. untuk menghitung luas lingkaran
3. untuk luas segitiga'''

pilihan=input(ket)

match pilihan:
    case "1":
        print("kamu memilih 1 untuk menghitung persegi")
        sisi= int(input("masukan sisi:"))
        luasP=sisi*sisi
        print("luas persegi yang sisinya",sisi,"adalah", luasP)
    case "2":
        print("kamu memilih 2 untuk menghitung luas lingkaran")
        jari2= float(input("masukan jari2?"))
        luasL= 3,14*jari2*jari2
        print("luas lingkaran yang jari2nya", jari2,"adalah", int(luasL))
    case "3":
        print("kamu memilih 3 untuk menghitung luas segitiga")
        alas= int(input("masukan alas?"))
        tinggi=int(input("masukan tinggi?"))
        LuasS= 0.5*alas*tinggi
        print("luas alas segitiga yang alasnya", alas,"dan tingginya", tinggi, "adalah", int(LuasS))
    case _:
        print("salah memilih pilihan")